# Generated by Django 4.0.3 on 2022-11-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatMa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cardID', models.CharField(max_length=8)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
