# Generated by Django 4.0.3 on 2022-11-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MatMa', '0006_alter_log_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='MatMa.user', verbose_name='Name'),
        ),
    ]
