# Generated by Django 4.0.3 on 2022-11-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatMa', '0007_alter_log_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
