# Generated by Django 4.0.3 on 2022-11-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MatMa', '0008_alter_log_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
    ]
